### ISSUE TITLE
Gist shortcode layout seems broken

### ISSUE THREAD

**Issue by simonszu** [parsiya/Hugo-Octopress#42]
Hi,
either this theme does not support it, or gist's delivery method changed. However, the output of the `gist` shortcode looks incomplete and broken. For reference, see [here](https://blog.simonszu.de/2017/09/luftdaten-mqtt-gateway-f%C3%BCr-den-feinstaubsensor/) (at the bottom). Notice the missing syntax highlighting, and the serif font. 

How could anybody fix this?

**Comment by parsiya** [comment]
The `gist` shortcode was not in Hugo when I made the theme so I never tried it. Let me look at it and see what the output looks like. It has some syntax highlighting but not what we want. The way the CSS works (because it's lifted directly from Octopress), the CSS has the highlights. The gist shortcode creates a class named `gist` so I might need to see how I can apply the same highlighting to it in css.

**Comment by parsiya** [comment]
See this branch: https://github.com/parsiya/Hugo-Octopress/tree/gist-fix

Github CSS was overiding the blog CSS. Not all of it looks exactly the same because Github and Pygments do it differently at times.

I still need to tweak the CSS if we want them to look exactly the same (for example the line numbers) but it works for now.

Here's what it looks like, the top ones are the gists and then you have the codecaption shortcode:

![image](https://user-images.githubusercontent.com/3981231/32589367-1a4def2c-c4e2-11e7-88ce-70ddc6aa24ff.png)

**Comment by parsiya** [comment]
I merged that branch into master.

**Comment by simonszu** [comment]
Nice, looks good. Thank you very much.

**Comment by parsiya** [comment]
Great, let me know if other stuff is broken.
