### ISSUE TITLE
Tag/Category sidebar menu page isn't generating links to posts

### ISSUE THREAD

**Issue by nllspc** [parsiya/Hugo-Octopress#48]
On the tag menu page (for example), the tags and counts are displayed but if you click a tag, it doesn't take you to a page with all the posts corresponding to that tag. I've tried working on this but I'm barely HTML literate and haven't made any headway. Was hoping you could help.

**Comment by parsiya** [comment]
Sorry this has happened, I can see it happening on your deployed website from your Github repository.

Did you rebuild the website with the "hugo" command after you updated it? Running "hugo" will create the website and store everything in "public." After you do, inside "public\tags" and "public\categories" you should see a directory for each tag or category. Inside you should see an "index.html"

I am not sure how Netlify works but with AWS Cloudfront, my uploaded files are not updated in real-time due to caching. I either have to go in and invalidate the cache or wait a few hours. But it could be completely different on your side.

**Comment by nllspc** [comment]
I have a directory for each tag/category but only an index.xml in each directory. Netlify is connected to my github acct so my website gets updated in real-time once I push locally.

**Comment by parsiya** [comment]
Seems like indexes were removed and that's why it has stopped working. See linked item.

**Comment by parsiya** [comment]
I have merged the pull request and removed the items from config. This should work now, if it does not please re-open the issue.
